version: '3'
services:

  ta_trader_LTC:
    build: .
    image: ta_trader_img
    container_name: ta_trader_LTC
    entrypoint: python live_trader.py -n WillRBband_LTC_3m_60m
    networks:
      - net
    volumes:
      - ./logs/docker/LTC/:/crypto_momentum/logs
    environment:
        - BINANCE_KEY=${BINANCE_KEY}
        - BINANCE_SECRET=${BINANCE_SECRET}
        - AWS_SNS_KEY=${AWS_SNS_KEY}
        - AWS_SNS_SECRET=${AWS_SNS_SECRET}
        - INFLUXDB_ADDR=${INFLUXDB_ADDR}
        - INFLUXDB_USER=${INFLUXDB_USER}
        - INFLUXDB_PW=${INFLUXDB_PW}

  ta_trader_XLM:
    build: .
    image: ta_trader_img
    container_name: ta_trader_XLM
    entrypoint: python live_trader.py -n WillRBband_XLM_3m_60m
    networks:
      - net
    volumes:
      - ./logs/docker/XLM/:/crypto_momentum/logs
    environment:
        - BINANCE_KEY=${BINANCE_KEY}
        - BINANCE_SECRET=${BINANCE_SECRET}
        - AWS_SNS_KEY=${AWS_SNS_KEY}
        - AWS_SNS_SECRET=${AWS_SNS_SECRET}
        - INFLUXDB_ADDR=${INFLUXDB_ADDR}
        - INFLUXDB_USER=${INFLUXDB_USER}
        - INFLUXDB_PW=${INFLUXDB_PW}

  ta_trader_BCH:
    build: .
    image: ta_trader_img
    container_name: ta_trader_BCH
    entrypoint: python live_trader.py -n WillRBband_BCH_3m_60m
    networks:
      - net
    volumes:
      - ./logs/docker/BCH/:/crypto_momentum/logs
    environment:
        - BINANCE_KEY=${BINANCE_KEY}
        - BINANCE_SECRET=${BINANCE_SECRET}
        - AWS_SNS_KEY=${AWS_SNS_KEY}
        - AWS_SNS_SECRET=${AWS_SNS_SECRET}
        - INFLUXDB_ADDR=${INFLUXDB_ADDR}
        - INFLUXDB_USER=${INFLUXDB_USER}
        - INFLUXDB_PW=${INFLUXDB_PW}

  ta_trader_LINK:
    build: .
    image: ta_trader_img
    container_name: ta_trader_LINK
    entrypoint: python live_trader.py -n WillRBband_LINK_3m_60m
    networks:
      - net
    volumes:
      - ./logs/docker/LINK/:/crypto_momentum/logs
    environment:
        - BINANCE_KEY=${BINANCE_KEY}
        - BINANCE_SECRET=${BINANCE_SECRET}
        - AWS_SNS_KEY=${AWS_SNS_KEY}
        - AWS_SNS_SECRET=${AWS_SNS_SECRET}
        - INFLUXDB_ADDR=${INFLUXDB_ADDR}
        - INFLUXDB_USER=${INFLUXDB_USER}
        - INFLUXDB_PW=${INFLUXDB_PW}

networks:
   net:
       driver: bridge
